{
  "_from": "fastify-error@^0.3.0",
  "_id": "fastify-error@0.3.1",
  "_inBundle": false,
  "_integrity": "sha512-oCfpcsDndgnDVgiI7bwFKAun2dO+4h84vBlkWsWnz/OUK9Reff5UFoFl241xTiLeHWX/vU9zkDVXqYUxjOwHcQ==",
  "_location": "/fastify-error",
  "_phantomChildren": {},
  "_requested": {
    "type": "range",
    "registry": true,
    "raw": "fastify-error@^0.3.0",
    "name": "fastify-error",
    "escapedName": "fastify-error",
    "rawSpec": "^0.3.0",
    "saveSpec": null,
    "fetchSpec": "^0.3.0"
  },
  "_requiredBy": [
    "/fastify"
  ],
  "_resolved": "https://registry.npmjs.org/fastify-error/-/fastify-error-0.3.1.tgz",
  "_shasum": "8eb993e15e3cf57f0357fc452af9290f1c1278d2",
  "_spec": "fastify-error@^0.3.0",
  "_where": "/private/var/mobile/Containers/Data/Application/DA8408CB-BA2C-4414-9E97-3E1E2AAF9607/Documents/apps/B1964C-CD59-42C6-B3F3-C2ABEC3783F8EED16CC-A610-4E4B-894E-BFB3D9C40459/src/node_modules/fastify",
  "author": {
    "name": "Tomas Della Vedova"
  },
  "bugs": {
    "url": "https://github.com/fastify/fastify-error/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "A small utility, used by Fastify itself, for generating consistent error objects across your codebase and plugins.",
  "devDependencies": {
    "@types/node": "^14.14.14",
    "ava": "^3.9.0",
    "standard": "^16.0.3",
    "tsd": "^0.14.0",
    "typescript": "^4.1.3"
  },
  "homepage": "https://github.com/fastify/fastify-error#readme",
  "keywords": [
    "fastify",
    "error",
    "utility",
    "plugin"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "fastify-error",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/fastify/fastify-error.git"
  },
  "scripts": {
    "test": "standard && ava -v && tsd"
  },
  "tsd": {
    "compilerOptions": {
      "esModuleInterop": true
    }
  },
  "types": "index.d.ts",
  "version": "0.3.1"
}
